name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 'stable'
      - name: Install packages needed for GLFW
        run: |
          sudo apt install -y libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libgl-dev libxxf86vm-dev
      - name: Nimble build
        run: |
          nimble install -y -d
          nimble androidPackage
      - name: Upload built package
        uses: actions/upload-artifact@v2
        with:
          name: Animdustry-SMOL-build
          path: android/build/outputs/apk/debug/android-debug.apk
